//auth
export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';
//GET USERS
export const FETCH_USERS = 'FETCH_USERS';
export const SEARCH_USER = 'SEARCH_USER';
export const FETCH_USER_BY_PREFIX = 'FETCH_USER_BY_PREFIX';
export const FETCH_USER_SERCHED = 'FETCH_USER_SERCHED';
export const FETCH_USERS_BY_ID = 'FETCH_USERS_BY_ID';
// UPDATE USER
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const CAPTURE_ID = 'CAPTURE_ID';

//SEND REPLY
export const REPLY_SEND = 'REPLY_SEND';
export const REPLY_DELETE = 'REPLY_DELETE';

//BLOGS
export const BLOG_PUBLISH = 'BLOG_PUBLISH';
export const BLOG_DELETE = 'BLOG_DELETE';
export const FETCH_BLOGS_BY_USER = 'FETCH_BLOGS_BY_USER';
export const FETCH_ALL_BLOGS = 'FETCH_ALL_BLOGS';


